export const state = {
  practiceQuestion: null,
  interviewSessionId: null,
  hrInterviewContext: null,
  hrCurrentQuestion: null,
  interviewFinished: false,
  busyCount: 0,
  questionCache: [],
  editingQuestionId: null,
  interviewLogs: [],
  resumeHistory: [],
  jobs: [],
  jobSearchQuery: "",
  jobVectorStatus: null,
};
