export const state = {
  practiceQuestion: null,
  interviewSessionId: null,
  hrInterviewContext: null,
  hrCurrentQuestion: null,
  interviewFinished: false,
  busyCount: 0,
  questionCache: [],
  interviewLogs: [],
  hrInterviewSessions: [],
  selectedInterviewReport: null,
  interviewRecordsExpanded: false,
  resumeHistory: [],
  jobs: [],
  jobSearchQuery: "",
  jobVectorStatus: null,
};
